name: commit-msg

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
    - shell: bash
      run: |
        pip install pre-commit
        pre-commit install --install-hooks -t commit-msg
        for commit in $(git rev-list ${{ github.base_ref }}..${{ github.head_ref }}); do
            git log -1 --format=%s $commit >| commit_msg.txt
            pre-commit run --hook-stage commit-msg --commit-msg-filename commit_msg.txt
        done
